using System.ComponentModel.DataAnnotations;
using HanyOptics.Domain.Enums;

namespace HanyOptics.BusinessLogic.Models;

// One frame being entered into stock.
//
// No barcode field: the shop's label is printed *after* the frame is in the system, so the
// code is generated by sp_generate_barcode from the sell price rather than typed. That is
// also why the price is required - the barcode cannot exist without it.
public class AddFrameRequest
{
    public FrameTrackingType TrackingType { get; set; } = FrameTrackingType.Individual;
    public FrameCategory Category { get; set; } = FrameCategory.Optical;

    [Required(ErrorMessage = "أدخل الماركة")]
    [StringLength(100)]
    public string? Brand { get; set; }

    [StringLength(100)]
    public string? ModelName { get; set; }

    [StringLength(50)]
    public string? Color { get; set; }

    [StringLength(20)]
    public string? Size { get; set; }

    // Nullable so an untouched form shows an empty box rather than a 0. A plain decimal
    // defaults to zero and renders as "0", which reads like a price someone entered - and
    // on the sell price that is the difference between "not filled in yet" and "free".
    [Range(0, 999999, ErrorMessage = "التكلفة غير صحيحة")]
    public decimal? CostPrice { get; set; }

    [Required(ErrorMessage = "أدخل سعر البيع — الباركود بيتولّد منه")]
    [Range(0.01, 999999, ErrorMessage = "سعر البيع غير صحيح")]
    public decimal? SellPrice { get; set; }

    // Ignored for an individual frame, which is a single physical piece by definition -
    // the service forces it to 1 rather than trusting whatever the form posted.
    [Range(1, 10000, ErrorMessage = "الكمية غير صحيحة")]
    public int Quantity { get; set; } = 1;

    [StringLength(500)]
    public string? Notes { get; set; }
}

public class AddFrameOutcome
{
    public bool Succeeded { get; init; }
    public int FrameId { get; init; }

    // The code sp_generate_barcode produced. The whole point of saving is to get this back:
    // it is what goes on the printed label, so the screen shows it rather than making
    // someone go and look the frame up again.
    public string? Barcode { get; init; }

    public string? ErrorMessage { get; init; }

    public static AddFrameOutcome Success(int frameId, string barcode) =>
        new() { Succeeded = true, FrameId = frameId, Barcode = barcode };

    public static AddFrameOutcome Failure(string message) => new() { ErrorMessage = message };
}
